name: "Ecr image"
description: 'Ecr Repo Check And Image Push Script'
inputs:
  AWS_ACCOUNT_ID:
    description: 'A Github AWS_ACCOUNT_ID'
    required: true
  AWS_PROFILE:
    description: 'A Github AWS_PROFILE'
    required: true
  AWS_DEFAULT_REGION:
    description: 'A Github AWS_DEFAULT_REGION'
    required: true
  GITHUB_COMMIT_HASH:
    description: 'A Github GITHUB_COMMIT_HASH'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check ECR Repository
<<<<<<< HEAD
      run: bash infrastructure/scripts/ecr_repo_check_prod.sh
=======
      run: bash infrastructure/scripts/ecr_rpo_check_prod.sh
>>>>>>> ef7b2fe81bef31f625e896791ce804274333eb66
      env:
        AWS_PROFILE: ${{ inputs.AWS_PROFILE }}
      shell: bash
            
    - name: Push Image in ECR
<<<<<<< HEAD
      run: bash infrastructure/scripts/image_push_prod.sh
=======
      run: bash infrastructure/scripts/image_push_code_prod.sh
>>>>>>> ef7b2fe81bef31f625e896791ce804274333eb66
      env:
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
          AWS_PROFILE: ${{ inputs.AWS_PROFILE }}
          GITHUB_COMMIT_HASH: ${{ inputs.GITHUB_COMMIT_HASH}}
      shell: bash

