#!/bin/bash


if [[ ${GIT_REF} == 'refs/heads/task_review' ]]; then
    echo "my_var=Dev" >> $GITHUB_OUTPUT
elif [[ ${GIT_REF} == 'refs/heads/feat/prod' ]]; then
    echo "my_var=Prod" >> $GITHUB_OUTPUT
fi