#!/bin/bash

echo "AWS Region: $AWS_REGIONS1"
echo "AWS Profile: $AWS_PROFILES1"

aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}" --profile "${AWS_PROFILES1}"
aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}" --profile "${AWS_PROFILES1}"
aws configure set region "${AWS_REGIONS1}" --profile "${AWS_PROFILES1}"
echo "AWS Access Key ID: $AWS_ACCESS_KEY_ID"