#!/bin/bash

echo "AWS Region: $aws_region"
echo "AWS Profile: $aws_profile"

aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}" --profile "${aws_profile}"
aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}" --profile "${aws_region}"
aws configure set region "${aws_region}" --profile "${aws_region}"
echo "AWS Access Key ID: $AWS_ACCESS_KEY_ID"