#!/bin/bash


echo "AWS Account ID: $AWS_ACCOUNT_ID"
echo "AWS Region: $_AWS_REGIONS"
echo "AWS Profile: $_AWS_PROFILES"
echo "GitHub Commit Hash: $GITHUB_COMMIT_HASH"

echo "AWS Access Key ID: $AWS_ACCOUNT_ID"
aws ecr get-login-password --region "${_AWS_REGIONS}" --profile "${_AWS_PROFILES}" | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}".dkr.ecr."${_AWS_REGIONS}".amazonaws.com
docker build -t "lambda-function-image" .
docker tag "lambda-function-image" "${AWS_ACCOUNT_ID}".dkr.ecr."${_AWS_REGIONS}".amazonaws.com/"${prefix}"-ecr:latest
docker push "${AWS_ACCOUNT_ID}".dkr.ecr."${_AWS_REGIONS}".amazonaws.com/"${prefix}"-ecr:latest

docker tag "lambda-function-image" "${AWS_ACCOUNT_ID}".dkr.ecr."${_AWS_REGIONS}".amazonaws.com/"${prefix}"-ecr:"${GITHUB_COMMIT_HASH}"
docker push "${AWS_ACCOUNT_ID}".dkr.ecr."${_AWS_REGIONS}".amazonaws.com/"${prefix}"-ecr:"${GITHUB_COMMIT_HASH}"
