name: "Configuration"
description: "Configuration of AWS and install Terraform, Terragrunt"

inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS Access Key ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS Secret Access Key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configuration AWS
      run: make aws_config
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
      shell: bash