name: "Push event"
on:
  push:
    branches:
      - task_review

jobs:
    Pulls-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        environment:
          name: "Dev"
        steps:
            - name: "Checkout Repo"
              uses: actions/checkout@v4

            - name: Aws Credentials Configuration
              uses:  ./.github/actions/aws_configuration 
              with:
                AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
                AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
                AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
                AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
                AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'

            - name: Terragrunt && Terraform Installation
              uses: ./.github/actions/terragrunt_terraform_install

            - name: Terragrunt initlization
              run: make init
            
            - name: Terragrunt plan Configuration
              run: make plan

    Push-Request:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        environment:
          name: "Dev"
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
        
          - name: Aws Credentials Configuration
            uses: ./.github/actions/aws_configuration
            with:
                AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
          - name: Terragrunt && Terraform Installation
            uses: ./.github/actions/terragrunt_terraform_install

          - name: Terragrunt initlization
            run: make init
          
          - name: Image Push Script
            run: make image_push
            env:
                AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
                AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
                GITHUB_COMMIT_HASH: '${{ github.sha }}'
                
          - name: Terragrunt plan Configuration
            run: make plan
          
          - name: Terragrunt apply Configuration
            run: make apply-ci