name: "Push Event And Pull Event"

on:
  push:
    branches:
      - feat/prod
  pull_request:
    branches:
      - feat/prod

jobs:
  pull-job:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Aws Credentials Configuration
        uses: ./.github/actions/aws_configuration
        with:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terragrunt && Terraform Installation
        uses: ./.github/actions/terragrunt_terraform_install

      - name: Terragrunt plan Configuration
        run: make plan

      - name: Image Build
        run: make image-build

  push-job:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Aws Credentials Configuration
        uses: ./.github/actions/aws_configuration
        with:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terragrunt && Terraform Installation
        uses: ./.github/actions/terragrunt_terraform_install

      - name: Image Push Script
        run: make build-push
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Terragrunt plan Configuration
        run: make plan

      - name: Terragrunt apply Configuration
        run: make apply-ci
