name: "Push event"
on:
    push:
        branches:
            - feat/terragrunt
jobs:
    Job1:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repo"
              uses: actions/checkout@v4

            - name: "Aws,Terraform && Terrgrunt Configuration"
              uses:  ./.github/actions/aws_terragrunt_configuration 
              with:
                AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
                AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
                AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
                AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
                AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'

            - name: Initialize Terragrunt
              working-directory: infrastructure/enviroments/dev/
              run: |
                terragrunt init